export const HOME_PATH = '/home'
export const LOGIN_PATH = '/login'
export const LOGOUT_PATH = '/logout'
export const PROFILE_PATH = '/profile'
export const REGISTER_PATH = '/register'
export const SWAPPER_PATH = '/swapper'
export const TERMS_AND_CONDITIONS_PATH = '/terms_and_conditions'
